### ISSUE TITLE
Deploy fails trying to find website directory

### ISSUE THREAD

**Issue by weisisheng** [turnerlabs/s3-docusaurus-sync-action#3]
The code is fairly straightforward but I don't know Alpine well.  This error surfaces, '/entrypoint.sh: cd: line 41: can't cd to website: No such file or directory'  All secrets are set on github.  Tried to prefix a slash to the dir name and also swap out for project name but no luck. 

Would appreciate any tips or tricks.  TIA.

**Comment by brockneedscoffee** [comment]
@weisisheng I am no longer at turner/warnermedia so I published a new GitHub action that supports latetest version of Docusaurus and corrects this issue, go take a look https://github.com/marketplace/actions/docusaurus-v2-s3-sync

**Comment by weisisheng** [comment]
Thanks!
